name: ecommerce
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localization: ^0.1.11
  flutter_localizations:
    sdk: flutter
  flutter_staggered_grid_view: ^0.6.2
  http: ^1.0.0
  path: ^1.8.3
  shared_preferences: ^2.1.1
  sqflite: ^2.2.8+4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: MessiriFont
      fonts:
        - asset: assets/fonts/ElMessiri-VariableFont_wght.ttf
