name: ecommerce
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  dropdown_search: ^5.0.6
  flutter:
    sdk: flutter
  flutter_localization: ^0.1.11
  flutter_localizations:
    sdk: flutter
  flutter_staggered_grid_view: ^0.6.2
  http: ^1.0.0
  intl_phone_field: ^3.2.0
  onesignal_flutter: ^3.5.1
  path: ^1.8.3
  permission_handler: ^10.4.3
  pinput: ^2.2.31
  share_plus: ^7.0.2
  shared_preferences: ^2.1.1
  smooth_page_indicator: ^1.1.0
  sqflite: ^2.2.8+4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: MessiriFont
      fonts:
        - asset: assets/fonts/ElMessiri-VariableFont_wght.ttf
