// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl4xhIx8nTJ3nuk9u6Jqq-tq6IifdGXVM',
    appId: '1:131629533317:web:55bacada8aef2591fec1ec',
    messagingSenderId: '131629533317',
    projectId: 'sooqin',
    authDomain: 'sooqin.firebaseapp.com',
    storageBucket: 'sooqin.appspot.com',
    measurementId: 'G-1BMPR8VL84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFg92nTdsrV8KZEO4c98qek52Dk1zsoYY',
    appId: '1:131629533317:android:097427eb2e91cc27fec1ec',
    messagingSenderId: '131629533317',
    projectId: 'sooqin',
    storageBucket: 'sooqin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-qzqSOIH1pJGK_G7gl5VJvSGlHrpB5Ok',
    appId: '1:131629533317:ios:e3d05a64eb5b9e02fec1ec',
    messagingSenderId: '131629533317',
    projectId: 'sooqin',
    storageBucket: 'sooqin.appspot.com',
    androidClientId:
        '131629533317-du7afi28j4cb86acebcjvnsmk7dk5nq7.apps.googleusercontent.com',
    iosClientId:
        '131629533317-12ol38du4bof4g9s3u1dhn4nse9gsako.apps.googleusercontent.com',
    iosBundleId: 'in.sooq.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-qzqSOIH1pJGK_G7gl5VJvSGlHrpB5Ok',
    appId: '1:131629533317:ios:548243d99b9eabfffec1ec',
    messagingSenderId: '131629533317',
    projectId: 'sooqin',
    storageBucket: 'sooqin.appspot.com',
    androidClientId:
        '131629533317-du7afi28j4cb86acebcjvnsmk7dk5nq7.apps.googleusercontent.com',
    iosClientId:
        '131629533317-melp2rm5h1s0d1ta8dn8bbi8hv5vnvvp.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce.RunnerTests',
  );
}
